services:
  postgres:
    image: postgres:16
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: ${AUTH_DATABASE_USER}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
      AUTH_DATABASE_DBNAME: ${AUTH_DATABASE_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: