// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: catalog/v1/catalog_service.proto

package catalogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_ListSuppliers_FullMethodName                 = "/catalog.v1.CatalogService/ListSuppliers"
	CatalogService_GetSupplier_FullMethodName                   = "/catalog.v1.CatalogService/GetSupplier"
	CatalogService_CreateSupplier_FullMethodName                = "/catalog.v1.CatalogService/CreateSupplier"
	CatalogService_UpdateSupplier_FullMethodName                = "/catalog.v1.CatalogService/UpdateSupplier"
	CatalogService_DeleteSupplier_FullMethodName                = "/catalog.v1.CatalogService/DeleteSupplier"
	CatalogService_ListCategories_FullMethodName                = "/catalog.v1.CatalogService/ListCategories"
	CatalogService_GetCategory_FullMethodName                   = "/catalog.v1.CatalogService/GetCategory"
	CatalogService_CreateCategory_FullMethodName                = "/catalog.v1.CatalogService/CreateCategory"
	CatalogService_UpdateCategory_FullMethodName                = "/catalog.v1.CatalogService/UpdateCategory"
	CatalogService_DeleteCategory_FullMethodName                = "/catalog.v1.CatalogService/DeleteCategory"
	CatalogService_ListProducts_FullMethodName                  = "/catalog.v1.CatalogService/ListProducts"
	CatalogService_GetProduct_FullMethodName                    = "/catalog.v1.CatalogService/GetProduct"
	CatalogService_CreateProduct_FullMethodName                 = "/catalog.v1.CatalogService/CreateProduct"
	CatalogService_UpdateProduct_FullMethodName                 = "/catalog.v1.CatalogService/UpdateProduct"
	CatalogService_DeleteProduct_FullMethodName                 = "/catalog.v1.CatalogService/DeleteProduct"
	CatalogService_ListProductImages_FullMethodName             = "/catalog.v1.CatalogService/ListProductImages"
	CatalogService_GetProductImage_FullMethodName               = "/catalog.v1.CatalogService/GetProductImage"
	CatalogService_CreateProductImage_FullMethodName            = "/catalog.v1.CatalogService/CreateProductImage"
	CatalogService_UpdateProductImage_FullMethodName            = "/catalog.v1.CatalogService/UpdateProductImage"
	CatalogService_DeleteProductImage_FullMethodName            = "/catalog.v1.CatalogService/DeleteProductImage"
	CatalogService_ListProductAttributes_FullMethodName         = "/catalog.v1.CatalogService/ListProductAttributes"
	CatalogService_GetProductAttribute_FullMethodName           = "/catalog.v1.CatalogService/GetProductAttribute"
	CatalogService_CreateProductAttribute_FullMethodName        = "/catalog.v1.CatalogService/CreateProductAttribute"
	CatalogService_UpdateProductAttribute_FullMethodName        = "/catalog.v1.CatalogService/UpdateProductAttribute"
	CatalogService_DeleteProductAttribute_FullMethodName        = "/catalog.v1.CatalogService/DeleteProductAttribute"
	CatalogService_ListBrands_FullMethodName                    = "/catalog.v1.CatalogService/ListBrands"
	CatalogService_GetBrand_FullMethodName                      = "/catalog.v1.CatalogService/GetBrand"
	CatalogService_CreateBrand_FullMethodName                   = "/catalog.v1.CatalogService/CreateBrand"
	CatalogService_UpdateBrand_FullMethodName                   = "/catalog.v1.CatalogService/UpdateBrand"
	CatalogService_DeleteBrand_FullMethodName                   = "/catalog.v1.CatalogService/DeleteBrand"
	CatalogService_ListSupplierCategoryMappings_FullMethodName  = "/catalog.v1.CatalogService/ListSupplierCategoryMappings"
	CatalogService_GetSupplierCategoryMapping_FullMethodName    = "/catalog.v1.CatalogService/GetSupplierCategoryMapping"
	CatalogService_CreateSupplierCategoryMapping_FullMethodName = "/catalog.v1.CatalogService/CreateSupplierCategoryMapping"
	CatalogService_UpdateSupplierCategoryMapping_FullMethodName = "/catalog.v1.CatalogService/UpdateSupplierCategoryMapping"
	CatalogService_DeleteSupplierCategoryMapping_FullMethodName = "/catalog.v1.CatalogService/DeleteSupplierCategoryMapping"
	CatalogService_ListSupplierProductMappings_FullMethodName   = "/catalog.v1.CatalogService/ListSupplierProductMappings"
	CatalogService_GetSupplierProductMapping_FullMethodName     = "/catalog.v1.CatalogService/GetSupplierProductMapping"
	CatalogService_CreateSupplierProductMapping_FullMethodName  = "/catalog.v1.CatalogService/CreateSupplierProductMapping"
	CatalogService_UpdateSupplierProductMapping_FullMethodName  = "/catalog.v1.CatalogService/UpdateSupplierProductMapping"
	CatalogService_DeleteSupplierProductMapping_FullMethodName  = "/catalog.v1.CatalogService/DeleteSupplierProductMapping"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	ListSuppliers(ctx context.Context, in *ListSuppliersRequest, opts ...grpc.CallOption) (*ListSuppliersResponse, error)
	GetSupplier(ctx context.Context, in *GetSupplierRequest, opts ...grpc.CallOption) (*GetSupplierResponse, error)
	CreateSupplier(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*CreateSupplierResponse, error)
	UpdateSupplier(ctx context.Context, in *UpdateSupplierRequest, opts ...grpc.CallOption) (*UpdateSupplierResponse, error)
	DeleteSupplier(ctx context.Context, in *DeleteSupplierRequest, opts ...grpc.CallOption) (*DeleteSupplierResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	ListProductImages(ctx context.Context, in *ListProductImagesRequest, opts ...grpc.CallOption) (*ListProductImagesResponse, error)
	GetProductImage(ctx context.Context, in *GetProductImageRequest, opts ...grpc.CallOption) (*GetProductImageResponse, error)
	CreateProductImage(ctx context.Context, in *CreateProductImageRequest, opts ...grpc.CallOption) (*CreateProductImageResponse, error)
	UpdateProductImage(ctx context.Context, in *UpdateProductImageRequest, opts ...grpc.CallOption) (*UpdateProductImageResponse, error)
	DeleteProductImage(ctx context.Context, in *DeleteProductImageRequest, opts ...grpc.CallOption) (*DeleteProductImageResponse, error)
	ListProductAttributes(ctx context.Context, in *ListProductAttributesRequest, opts ...grpc.CallOption) (*ListProductAttributesResponse, error)
	GetProductAttribute(ctx context.Context, in *GetProductAttributeRequest, opts ...grpc.CallOption) (*GetProductAttributeResponse, error)
	CreateProductAttribute(ctx context.Context, in *CreateProductAttributeRequest, opts ...grpc.CallOption) (*CreateProductAttributeResponse, error)
	UpdateProductAttribute(ctx context.Context, in *UpdateProductAttributeRequest, opts ...grpc.CallOption) (*UpdateProductAttributeResponse, error)
	DeleteProductAttribute(ctx context.Context, in *DeleteProductAttributeRequest, opts ...grpc.CallOption) (*DeleteProductAttributeResponse, error)
	ListBrands(ctx context.Context, in *ListBrandsRequest, opts ...grpc.CallOption) (*ListBrandsResponse, error)
	GetBrand(ctx context.Context, in *GetBrandRequest, opts ...grpc.CallOption) (*GetBrandResponse, error)
	CreateBrand(ctx context.Context, in *CreateBrandRequest, opts ...grpc.CallOption) (*CreateBrandResponse, error)
	UpdateBrand(ctx context.Context, in *UpdateBrandRequest, opts ...grpc.CallOption) (*UpdateBrandResponse, error)
	DeleteBrand(ctx context.Context, in *DeleteBrandRequest, opts ...grpc.CallOption) (*DeleteBrandResponse, error)
	ListSupplierCategoryMappings(ctx context.Context, in *ListSupplierCategoryMappingsRequest, opts ...grpc.CallOption) (*ListSupplierCategoryMappingsResponse, error)
	GetSupplierCategoryMapping(ctx context.Context, in *GetSupplierCategoryMappingRequest, opts ...grpc.CallOption) (*GetSupplierCategoryMappingResponse, error)
	CreateSupplierCategoryMapping(ctx context.Context, in *CreateSupplierCategoryMappingRequest, opts ...grpc.CallOption) (*CreateSupplierCategoryMappingResponse, error)
	UpdateSupplierCategoryMapping(ctx context.Context, in *UpdateSupplierCategoryMappingRequest, opts ...grpc.CallOption) (*UpdateSupplierCategoryMappingResponse, error)
	DeleteSupplierCategoryMapping(ctx context.Context, in *DeleteSupplierCategoryMappingRequest, opts ...grpc.CallOption) (*DeleteSupplierCategoryMappingResponse, error)
	ListSupplierProductMappings(ctx context.Context, in *ListSupplierProductMappingsRequest, opts ...grpc.CallOption) (*ListSupplierProductMappingsResponse, error)
	GetSupplierProductMapping(ctx context.Context, in *GetSupplierProductMappingRequest, opts ...grpc.CallOption) (*GetSupplierProductMappingResponse, error)
	CreateSupplierProductMapping(ctx context.Context, in *CreateSupplierProductMappingRequest, opts ...grpc.CallOption) (*CreateSupplierProductMappingResponse, error)
	UpdateSupplierProductMapping(ctx context.Context, in *UpdateSupplierProductMappingRequest, opts ...grpc.CallOption) (*UpdateSupplierProductMappingResponse, error)
	DeleteSupplierProductMapping(ctx context.Context, in *DeleteSupplierProductMappingRequest, opts ...grpc.CallOption) (*DeleteSupplierProductMappingResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ListSuppliers(ctx context.Context, in *ListSuppliersRequest, opts ...grpc.CallOption) (*ListSuppliersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSuppliersResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListSuppliers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetSupplier(ctx context.Context, in *GetSupplierRequest, opts ...grpc.CallOption) (*GetSupplierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupplierResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetSupplier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateSupplier(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*CreateSupplierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupplierResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateSupplier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateSupplier(ctx context.Context, in *UpdateSupplierRequest, opts ...grpc.CallOption) (*UpdateSupplierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSupplierResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateSupplier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteSupplier(ctx context.Context, in *DeleteSupplierRequest, opts ...grpc.CallOption) (*DeleteSupplierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSupplierResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteSupplier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListProductImages(ctx context.Context, in *ListProductImagesRequest, opts ...grpc.CallOption) (*ListProductImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductImagesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListProductImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProductImage(ctx context.Context, in *GetProductImageRequest, opts ...grpc.CallOption) (*GetProductImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductImageResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetProductImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateProductImage(ctx context.Context, in *CreateProductImageRequest, opts ...grpc.CallOption) (*CreateProductImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductImageResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateProductImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateProductImage(ctx context.Context, in *UpdateProductImageRequest, opts ...grpc.CallOption) (*UpdateProductImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductImageResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateProductImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteProductImage(ctx context.Context, in *DeleteProductImageRequest, opts ...grpc.CallOption) (*DeleteProductImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductImageResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteProductImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListProductAttributes(ctx context.Context, in *ListProductAttributesRequest, opts ...grpc.CallOption) (*ListProductAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductAttributesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListProductAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProductAttribute(ctx context.Context, in *GetProductAttributeRequest, opts ...grpc.CallOption) (*GetProductAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductAttributeResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetProductAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateProductAttribute(ctx context.Context, in *CreateProductAttributeRequest, opts ...grpc.CallOption) (*CreateProductAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductAttributeResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateProductAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateProductAttribute(ctx context.Context, in *UpdateProductAttributeRequest, opts ...grpc.CallOption) (*UpdateProductAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductAttributeResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateProductAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteProductAttribute(ctx context.Context, in *DeleteProductAttributeRequest, opts ...grpc.CallOption) (*DeleteProductAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductAttributeResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteProductAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListBrands(ctx context.Context, in *ListBrandsRequest, opts ...grpc.CallOption) (*ListBrandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBrandsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListBrands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetBrand(ctx context.Context, in *GetBrandRequest, opts ...grpc.CallOption) (*GetBrandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBrandResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateBrand(ctx context.Context, in *CreateBrandRequest, opts ...grpc.CallOption) (*CreateBrandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBrandResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateBrand(ctx context.Context, in *UpdateBrandRequest, opts ...grpc.CallOption) (*UpdateBrandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBrandResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteBrand(ctx context.Context, in *DeleteBrandRequest, opts ...grpc.CallOption) (*DeleteBrandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBrandResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListSupplierCategoryMappings(ctx context.Context, in *ListSupplierCategoryMappingsRequest, opts ...grpc.CallOption) (*ListSupplierCategoryMappingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupplierCategoryMappingsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListSupplierCategoryMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetSupplierCategoryMapping(ctx context.Context, in *GetSupplierCategoryMappingRequest, opts ...grpc.CallOption) (*GetSupplierCategoryMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupplierCategoryMappingResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetSupplierCategoryMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateSupplierCategoryMapping(ctx context.Context, in *CreateSupplierCategoryMappingRequest, opts ...grpc.CallOption) (*CreateSupplierCategoryMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupplierCategoryMappingResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateSupplierCategoryMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateSupplierCategoryMapping(ctx context.Context, in *UpdateSupplierCategoryMappingRequest, opts ...grpc.CallOption) (*UpdateSupplierCategoryMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSupplierCategoryMappingResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateSupplierCategoryMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteSupplierCategoryMapping(ctx context.Context, in *DeleteSupplierCategoryMappingRequest, opts ...grpc.CallOption) (*DeleteSupplierCategoryMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSupplierCategoryMappingResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteSupplierCategoryMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListSupplierProductMappings(ctx context.Context, in *ListSupplierProductMappingsRequest, opts ...grpc.CallOption) (*ListSupplierProductMappingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupplierProductMappingsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListSupplierProductMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetSupplierProductMapping(ctx context.Context, in *GetSupplierProductMappingRequest, opts ...grpc.CallOption) (*GetSupplierProductMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupplierProductMappingResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetSupplierProductMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateSupplierProductMapping(ctx context.Context, in *CreateSupplierProductMappingRequest, opts ...grpc.CallOption) (*CreateSupplierProductMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupplierProductMappingResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateSupplierProductMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateSupplierProductMapping(ctx context.Context, in *UpdateSupplierProductMappingRequest, opts ...grpc.CallOption) (*UpdateSupplierProductMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSupplierProductMappingResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateSupplierProductMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteSupplierProductMapping(ctx context.Context, in *DeleteSupplierProductMappingRequest, opts ...grpc.CallOption) (*DeleteSupplierProductMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSupplierProductMappingResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteSupplierProductMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	ListSuppliers(context.Context, *ListSuppliersRequest) (*ListSuppliersResponse, error)
	GetSupplier(context.Context, *GetSupplierRequest) (*GetSupplierResponse, error)
	CreateSupplier(context.Context, *CreateSupplierRequest) (*CreateSupplierResponse, error)
	UpdateSupplier(context.Context, *UpdateSupplierRequest) (*UpdateSupplierResponse, error)
	DeleteSupplier(context.Context, *DeleteSupplierRequest) (*DeleteSupplierResponse, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	ListProductImages(context.Context, *ListProductImagesRequest) (*ListProductImagesResponse, error)
	GetProductImage(context.Context, *GetProductImageRequest) (*GetProductImageResponse, error)
	CreateProductImage(context.Context, *CreateProductImageRequest) (*CreateProductImageResponse, error)
	UpdateProductImage(context.Context, *UpdateProductImageRequest) (*UpdateProductImageResponse, error)
	DeleteProductImage(context.Context, *DeleteProductImageRequest) (*DeleteProductImageResponse, error)
	ListProductAttributes(context.Context, *ListProductAttributesRequest) (*ListProductAttributesResponse, error)
	GetProductAttribute(context.Context, *GetProductAttributeRequest) (*GetProductAttributeResponse, error)
	CreateProductAttribute(context.Context, *CreateProductAttributeRequest) (*CreateProductAttributeResponse, error)
	UpdateProductAttribute(context.Context, *UpdateProductAttributeRequest) (*UpdateProductAttributeResponse, error)
	DeleteProductAttribute(context.Context, *DeleteProductAttributeRequest) (*DeleteProductAttributeResponse, error)
	ListBrands(context.Context, *ListBrandsRequest) (*ListBrandsResponse, error)
	GetBrand(context.Context, *GetBrandRequest) (*GetBrandResponse, error)
	CreateBrand(context.Context, *CreateBrandRequest) (*CreateBrandResponse, error)
	UpdateBrand(context.Context, *UpdateBrandRequest) (*UpdateBrandResponse, error)
	DeleteBrand(context.Context, *DeleteBrandRequest) (*DeleteBrandResponse, error)
	ListSupplierCategoryMappings(context.Context, *ListSupplierCategoryMappingsRequest) (*ListSupplierCategoryMappingsResponse, error)
	GetSupplierCategoryMapping(context.Context, *GetSupplierCategoryMappingRequest) (*GetSupplierCategoryMappingResponse, error)
	CreateSupplierCategoryMapping(context.Context, *CreateSupplierCategoryMappingRequest) (*CreateSupplierCategoryMappingResponse, error)
	UpdateSupplierCategoryMapping(context.Context, *UpdateSupplierCategoryMappingRequest) (*UpdateSupplierCategoryMappingResponse, error)
	DeleteSupplierCategoryMapping(context.Context, *DeleteSupplierCategoryMappingRequest) (*DeleteSupplierCategoryMappingResponse, error)
	ListSupplierProductMappings(context.Context, *ListSupplierProductMappingsRequest) (*ListSupplierProductMappingsResponse, error)
	GetSupplierProductMapping(context.Context, *GetSupplierProductMappingRequest) (*GetSupplierProductMappingResponse, error)
	CreateSupplierProductMapping(context.Context, *CreateSupplierProductMappingRequest) (*CreateSupplierProductMappingResponse, error)
	UpdateSupplierProductMapping(context.Context, *UpdateSupplierProductMappingRequest) (*UpdateSupplierProductMappingResponse, error)
	DeleteSupplierProductMapping(context.Context, *DeleteSupplierProductMappingRequest) (*DeleteSupplierProductMappingResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) ListSuppliers(context.Context, *ListSuppliersRequest) (*ListSuppliersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSuppliers not implemented")
}
func (UnimplementedCatalogServiceServer) GetSupplier(context.Context, *GetSupplierRequest) (*GetSupplierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupplier not implemented")
}
func (UnimplementedCatalogServiceServer) CreateSupplier(context.Context, *CreateSupplierRequest) (*CreateSupplierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSupplier not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateSupplier(context.Context, *UpdateSupplierRequest) (*UpdateSupplierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSupplier not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteSupplier(context.Context, *DeleteSupplierRequest) (*DeleteSupplierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSupplier not implemented")
}
func (UnimplementedCatalogServiceServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedCatalogServiceServer) GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedCatalogServiceServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedCatalogServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedCatalogServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedCatalogServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedCatalogServiceServer) ListProductImages(context.Context, *ListProductImagesRequest) (*ListProductImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductImages not implemented")
}
func (UnimplementedCatalogServiceServer) GetProductImage(context.Context, *GetProductImageRequest) (*GetProductImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductImage not implemented")
}
func (UnimplementedCatalogServiceServer) CreateProductImage(context.Context, *CreateProductImageRequest) (*CreateProductImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductImage not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateProductImage(context.Context, *UpdateProductImageRequest) (*UpdateProductImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductImage not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteProductImage(context.Context, *DeleteProductImageRequest) (*DeleteProductImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductImage not implemented")
}
func (UnimplementedCatalogServiceServer) ListProductAttributes(context.Context, *ListProductAttributesRequest) (*ListProductAttributesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductAttributes not implemented")
}
func (UnimplementedCatalogServiceServer) GetProductAttribute(context.Context, *GetProductAttributeRequest) (*GetProductAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductAttribute not implemented")
}
func (UnimplementedCatalogServiceServer) CreateProductAttribute(context.Context, *CreateProductAttributeRequest) (*CreateProductAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductAttribute not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateProductAttribute(context.Context, *UpdateProductAttributeRequest) (*UpdateProductAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductAttribute not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteProductAttribute(context.Context, *DeleteProductAttributeRequest) (*DeleteProductAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductAttribute not implemented")
}
func (UnimplementedCatalogServiceServer) ListBrands(context.Context, *ListBrandsRequest) (*ListBrandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBrands not implemented")
}
func (UnimplementedCatalogServiceServer) GetBrand(context.Context, *GetBrandRequest) (*GetBrandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBrand not implemented")
}
func (UnimplementedCatalogServiceServer) CreateBrand(context.Context, *CreateBrandRequest) (*CreateBrandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBrand not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateBrand(context.Context, *UpdateBrandRequest) (*UpdateBrandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBrand not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteBrand(context.Context, *DeleteBrandRequest) (*DeleteBrandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBrand not implemented")
}
func (UnimplementedCatalogServiceServer) ListSupplierCategoryMappings(context.Context, *ListSupplierCategoryMappingsRequest) (*ListSupplierCategoryMappingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSupplierCategoryMappings not implemented")
}
func (UnimplementedCatalogServiceServer) GetSupplierCategoryMapping(context.Context, *GetSupplierCategoryMappingRequest) (*GetSupplierCategoryMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupplierCategoryMapping not implemented")
}
func (UnimplementedCatalogServiceServer) CreateSupplierCategoryMapping(context.Context, *CreateSupplierCategoryMappingRequest) (*CreateSupplierCategoryMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSupplierCategoryMapping not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateSupplierCategoryMapping(context.Context, *UpdateSupplierCategoryMappingRequest) (*UpdateSupplierCategoryMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSupplierCategoryMapping not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteSupplierCategoryMapping(context.Context, *DeleteSupplierCategoryMappingRequest) (*DeleteSupplierCategoryMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSupplierCategoryMapping not implemented")
}
func (UnimplementedCatalogServiceServer) ListSupplierProductMappings(context.Context, *ListSupplierProductMappingsRequest) (*ListSupplierProductMappingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSupplierProductMappings not implemented")
}
func (UnimplementedCatalogServiceServer) GetSupplierProductMapping(context.Context, *GetSupplierProductMappingRequest) (*GetSupplierProductMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupplierProductMapping not implemented")
}
func (UnimplementedCatalogServiceServer) CreateSupplierProductMapping(context.Context, *CreateSupplierProductMappingRequest) (*CreateSupplierProductMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSupplierProductMapping not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateSupplierProductMapping(context.Context, *UpdateSupplierProductMappingRequest) (*UpdateSupplierProductMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSupplierProductMapping not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteSupplierProductMapping(context.Context, *DeleteSupplierProductMappingRequest) (*DeleteSupplierProductMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSupplierProductMapping not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_ListSuppliers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSuppliersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListSuppliers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListSuppliers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListSuppliers(ctx, req.(*ListSuppliersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetSupplier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetSupplier(ctx, req.(*GetSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateSupplier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateSupplier(ctx, req.(*CreateSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateSupplier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateSupplier(ctx, req.(*UpdateSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteSupplier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteSupplier(ctx, req.(*DeleteSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListProductImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListProductImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListProductImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListProductImages(ctx, req.(*ListProductImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetProductImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProductImage(ctx, req.(*GetProductImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateProductImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateProductImage(ctx, req.(*CreateProductImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateProductImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateProductImage(ctx, req.(*UpdateProductImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteProductImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteProductImage(ctx, req.(*DeleteProductImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListProductAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListProductAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListProductAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListProductAttributes(ctx, req.(*ListProductAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProductAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProductAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetProductAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProductAttribute(ctx, req.(*GetProductAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateProductAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateProductAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateProductAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateProductAttribute(ctx, req.(*CreateProductAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateProductAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateProductAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateProductAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateProductAttribute(ctx, req.(*UpdateProductAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteProductAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteProductAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteProductAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteProductAttribute(ctx, req.(*DeleteProductAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBrandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListBrands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListBrands(ctx, req.(*ListBrandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetBrand(ctx, req.(*GetBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateBrand(ctx, req.(*CreateBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateBrand(ctx, req.(*UpdateBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteBrand(ctx, req.(*DeleteBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListSupplierCategoryMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupplierCategoryMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListSupplierCategoryMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListSupplierCategoryMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListSupplierCategoryMappings(ctx, req.(*ListSupplierCategoryMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetSupplierCategoryMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupplierCategoryMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetSupplierCategoryMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetSupplierCategoryMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetSupplierCategoryMapping(ctx, req.(*GetSupplierCategoryMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateSupplierCategoryMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierCategoryMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateSupplierCategoryMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateSupplierCategoryMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateSupplierCategoryMapping(ctx, req.(*CreateSupplierCategoryMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateSupplierCategoryMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupplierCategoryMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateSupplierCategoryMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateSupplierCategoryMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateSupplierCategoryMapping(ctx, req.(*UpdateSupplierCategoryMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteSupplierCategoryMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSupplierCategoryMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteSupplierCategoryMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteSupplierCategoryMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteSupplierCategoryMapping(ctx, req.(*DeleteSupplierCategoryMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListSupplierProductMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupplierProductMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListSupplierProductMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListSupplierProductMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListSupplierProductMappings(ctx, req.(*ListSupplierProductMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetSupplierProductMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupplierProductMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetSupplierProductMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetSupplierProductMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetSupplierProductMapping(ctx, req.(*GetSupplierProductMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateSupplierProductMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierProductMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateSupplierProductMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateSupplierProductMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateSupplierProductMapping(ctx, req.(*CreateSupplierProductMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateSupplierProductMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupplierProductMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateSupplierProductMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateSupplierProductMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateSupplierProductMapping(ctx, req.(*UpdateSupplierProductMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteSupplierProductMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSupplierProductMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteSupplierProductMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteSupplierProductMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteSupplierProductMapping(ctx, req.(*DeleteSupplierProductMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSuppliers",
			Handler:    _CatalogService_ListSuppliers_Handler,
		},
		{
			MethodName: "GetSupplier",
			Handler:    _CatalogService_GetSupplier_Handler,
		},
		{
			MethodName: "CreateSupplier",
			Handler:    _CatalogService_CreateSupplier_Handler,
		},
		{
			MethodName: "UpdateSupplier",
			Handler:    _CatalogService_UpdateSupplier_Handler,
		},
		{
			MethodName: "DeleteSupplier",
			Handler:    _CatalogService_DeleteSupplier_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _CatalogService_ListCategories_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _CatalogService_GetCategory_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _CatalogService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _CatalogService_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _CatalogService_DeleteCategory_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _CatalogService_ListProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _CatalogService_GetProduct_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _CatalogService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _CatalogService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _CatalogService_DeleteProduct_Handler,
		},
		{
			MethodName: "ListProductImages",
			Handler:    _CatalogService_ListProductImages_Handler,
		},
		{
			MethodName: "GetProductImage",
			Handler:    _CatalogService_GetProductImage_Handler,
		},
		{
			MethodName: "CreateProductImage",
			Handler:    _CatalogService_CreateProductImage_Handler,
		},
		{
			MethodName: "UpdateProductImage",
			Handler:    _CatalogService_UpdateProductImage_Handler,
		},
		{
			MethodName: "DeleteProductImage",
			Handler:    _CatalogService_DeleteProductImage_Handler,
		},
		{
			MethodName: "ListProductAttributes",
			Handler:    _CatalogService_ListProductAttributes_Handler,
		},
		{
			MethodName: "GetProductAttribute",
			Handler:    _CatalogService_GetProductAttribute_Handler,
		},
		{
			MethodName: "CreateProductAttribute",
			Handler:    _CatalogService_CreateProductAttribute_Handler,
		},
		{
			MethodName: "UpdateProductAttribute",
			Handler:    _CatalogService_UpdateProductAttribute_Handler,
		},
		{
			MethodName: "DeleteProductAttribute",
			Handler:    _CatalogService_DeleteProductAttribute_Handler,
		},
		{
			MethodName: "ListBrands",
			Handler:    _CatalogService_ListBrands_Handler,
		},
		{
			MethodName: "GetBrand",
			Handler:    _CatalogService_GetBrand_Handler,
		},
		{
			MethodName: "CreateBrand",
			Handler:    _CatalogService_CreateBrand_Handler,
		},
		{
			MethodName: "UpdateBrand",
			Handler:    _CatalogService_UpdateBrand_Handler,
		},
		{
			MethodName: "DeleteBrand",
			Handler:    _CatalogService_DeleteBrand_Handler,
		},
		{
			MethodName: "ListSupplierCategoryMappings",
			Handler:    _CatalogService_ListSupplierCategoryMappings_Handler,
		},
		{
			MethodName: "GetSupplierCategoryMapping",
			Handler:    _CatalogService_GetSupplierCategoryMapping_Handler,
		},
		{
			MethodName: "CreateSupplierCategoryMapping",
			Handler:    _CatalogService_CreateSupplierCategoryMapping_Handler,
		},
		{
			MethodName: "UpdateSupplierCategoryMapping",
			Handler:    _CatalogService_UpdateSupplierCategoryMapping_Handler,
		},
		{
			MethodName: "DeleteSupplierCategoryMapping",
			Handler:    _CatalogService_DeleteSupplierCategoryMapping_Handler,
		},
		{
			MethodName: "ListSupplierProductMappings",
			Handler:    _CatalogService_ListSupplierProductMappings_Handler,
		},
		{
			MethodName: "GetSupplierProductMapping",
			Handler:    _CatalogService_GetSupplierProductMapping_Handler,
		},
		{
			MethodName: "CreateSupplierProductMapping",
			Handler:    _CatalogService_CreateSupplierProductMapping_Handler,
		},
		{
			MethodName: "UpdateSupplierProductMapping",
			Handler:    _CatalogService_UpdateSupplierProductMapping_Handler,
		},
		{
			MethodName: "DeleteSupplierProductMapping",
			Handler:    _CatalogService_DeleteSupplierProductMapping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog/v1/catalog_service.proto",
}
