grpc_port: ":50051"
jwt_secret: ""
jwt_expiration_hours: 24
allowed_origins:
  - "http://localhost:4200"
cookie_secure: false

database:
  host: "localhost"
  port: 5432
  user: "auth_db_user"
  password: ""
  dbname: "auth_db"
  sslmode: "disable"